# Generated by Django 6.0.1 on 2026-07-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_seed_initial_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recoverable_password',
            field=models.TextField(blank=True, default=''),
        ),
    ]
