# Generated by Django 6.0.1 on 2026-07-04 07:07

from decimal import Decimal
from django.db import migrations, models


def apply_new_loan_range(apps, schema_editor):
    # New defaults only affect rows created from now on — this updates the
    # existing singleton row (or creates it) so the change takes effect
    # immediately without needing manual admin edits in production.
    LoanConfig = apps.get_model("accounts", "LoanConfig")
    cfg = LoanConfig.objects.first()
    if cfg:
        cfg.min_amount = Decimal("75000.00")
        cfg.max_amount = Decimal("2000000.00")
        cfg.save(update_fields=["min_amount", "max_amount"])
    else:
        LoanConfig.objects.create(
            min_amount=Decimal("75000.00"),
            max_amount=Decimal("2000000.00"),
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_user_recoverable_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanconfig',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('2000000.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='loanconfig',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('75000.00'), max_digits=14),
        ),
        migrations.RunPython(apply_new_loan_range, noop),
    ]
